package localizable

const UKRAINIAN = "uk"

// Ukrainian translation. Covers the most user-visible strings (navigation,
// send/receive/transactions, balances, settings, common errors). Missing keys
// fall back to the English file via values.String's per-language fallback.
const UK = `
"appName" = "Skarb"
"appTitle" = "Skarb Wallet (%s)"
"appWallet" = "Skarb Wallet"
"welcomeNote" = "Ласкаво просимо до Skarb Wallet — гаманця мережі Monetarium."

// Navigation
"home" = "Головна"
"overview" = "Огляд"
"send" = "Надіслати"
"receive" = "Отримати"
"transactions" = "Транзакції"
"settings" = "Налаштування"
"info" = "Інформація"
"accounts" = "Акаунти"
"account" = "Акаунт"
"wallets" = "Гаманці"
"wallet" = "Гаманець"
"createNewWallet" = "Створити новий гаманець"
"restoreExistingWallet" = "Відновити наявний гаманець"
"importWallet" = "Імпортувати гаманець"
"selectWallet" = "Оберіть гаманець"

// Common UI
"all" = "Усі"
"cancel" = "Скасувати"
"save" = "Зберегти"
"confirm" = "Підтвердити"
"continue" = "Продовжити"
"next" = "Далі"
"back" = "Назад"
"done" = "Готово"
"ok" = "Гаразд"
"yes" = "Так"
"no" = "Ні"
"close" = "Закрити"
"delete" = "Видалити"
"edit" = "Редагувати"
"copy" = "Копіювати"
"copied" = "Скопійовано"
"loading" = "Завантаження…"
"search" = "Пошук"
"filter" = "Фільтр"

// Balances
"balance" = "Баланс"
"totalBalance" = "Загальний баланс"
"labelSpendable" = "Доступний"
"unconfirmed" = "Непідтверджено"
"locked" = "Заблоковано"
"watchOnly" = "Лише перегляд"

// Send page
"amount" = "Сума"
"address" = "Адреса"
"destinationAddress" = "Адреса отримувача"
"sourceAccount" = "Акаунт-джерело"
"sourceWallet" = "Гаманець-джерело"
"fee" = "Комісія"
"feeRate" = "Ставка комісії"
"totalCost" = "Загальна сума"
"balanceAfterSend" = "Баланс після відправлення"
"balanceAfter" = "Баланс після відправлення"
"destinationMissing" = "Адреса отримувача не вказана"
"sameAddressReceivesHint" = "Адреса однакова для всіх активів. Попросіть відправника надіслати саме %s."
"myAddress" = "Моя адреса"
"nextAddress" = "Нова адреса"
"sendMax" = "Надіслати все"
"signAndSend" = "Підписати та надіслати"
"addRecipient" = "Додати отримувача"
"removeRecipient" = "Прибрати отримувача"
"invalidAmount" = "Некоректна сума"
"invalidAddress" = "Некоректна адреса"
"insufficientFund" = "Недостатньо коштів"

// Receive page
"yourAddress" = "Ваша адреса"
"generateNewAddress" = "Згенерувати нову адресу"
"warningWatchWallet" = "Увага: це гаманець лише для перегляду — отримання можливе, відправлення ні."

// Transactions
"recentTransactions" = "Останні транзакції"
"noTransactions" = "Транзакцій ще немає"
"transactionDetails" = "Деталі транзакції"
"sent" = "Надіслано"
"received" = "Отримано"
"transferred" = "Переказано"
"complete" = "Завершено"
"unconfirmedTx" = "Непідтверджено"
"newest" = "Найновіші"
"oldest" = "Найстаріші"

// Settings
"general" = "Загальні"
"language" = "Мова"
"english" = "English"
"ukrainian" = "Українська"
"french" = "French"
"spanish" = "Spanish"
"chinese" = "Chinese"
"darkMode" = "Темна тема"
"currency" = "Валюта"
"currencyConversion" = "Конвертація валют"
"about" = "Про програму"
"version" = "Версія"
"security" = "Безпека"
"changeSpendingPassword" = "Змінити пароль на витрачання"
"backupSeed" = "Резервна копія сід-фрази"
"viewSeed" = "Переглянути сід-фразу"
"verifySeed" = "Перевірити сід-фразу"

// Sync
"connecting" = "Підключення…"
"syncing" = "Синхронізація…"
"synced" = "Синхронізовано"
"notSynced" = "Не синхронізовано"
"startSync" = "Почати синхронізацію"
"stopSync" = "Зупинити синхронізацію"
"online" = "Онлайн, "
"offline" = "Офлайн, "
"connectedToPeers" = "Підключено до пірів: %d"

// Onboarding
"selectLanguage" = "Оберіть мову"
"selectNetwork" = "Оберіть мережу"
"mainnet" = "Mainnet"
"testnet" = "Testnet"
"createWallet" = "Створити гаманець"
"walletName" = "Назва гаманця"
"setSpendingPassword" = "Встановіть пароль на витрачання"
"confirmPassword" = "Підтвердіть пароль"
"passwordMismatch" = "Паролі не співпадають"
"passwordTooShort" = "Пароль закороткий"

// Errors
"error" = "Помилка"
"warning" = "Увага"
"unknown" = "Невідомо"
"failed" = "Не вдалося"
"tryAgain" = "Спробувати ще раз"
"invalidPassphrase" = "Неправильний пароль"
"insufficientFunds" = "Недостатньо коштів"
"walletNotLoaded" = "Гаманець не завантажено"
"syncAlreadyInProgress" = "Синхронізація вже триває"
"functionUnavailable" = "Функція недоступна"
"noInternet" = "Немає підключення до інтернету"

// Sync info
"blockHeaderFetched" = "Заголовків блоків отримано"
"blockHeaderFetchedCount" = "%d з %d"
"bestBlocks" = "Найкращий блок"
"blocksLeft" = "Залишилось блоків"
"blocksScanned" = "Відскановано блоків"
"addressDiscovering" = "Пошук адрес"
"addressDiscoveryStarted" = "Розпочато пошук адрес"
"addressDiscoveryInProgress" = "Триває пошук адрес"
"rescanProgress" = "Прогрес повторного сканування"
"syncProgressTitle" = "Прогрес синхронізації"
"latestBlock" = "Останній блок"
"connectedTo" = "Підключено до %d пірів"
"peersConnected" = "Підключені піри"
"connectToSpecificPeer" = "Підключатися до конкретного піра"
"viewSyncDetails" = "Деталі синхронізації"

// Send page details
"max" = "Макс"
"automatic" = "Автоматичний"
"manual" = "Ручний"
"coinSelection" = "Вибір UTXO"
"advancedOptions" = "Розширені налаштування"
"description" = "Опис"
"txDescriptionTitle" = "Опис транзакції (необовʼязково)"
"transactionFee" = "Комісія за транзакцію"
"signTransaction" = "Підписати транзакцію"
"reviewTransaction" = "Перевірте транзакцію"
"transactionConfirmed" = "Транзакцію підтверджено"
"broadcasting" = "Розсилання…"
"broadcastingTransaction" = "Розсилання транзакції"
"transactionSent" = "Транзакцію надіслано"
"unconfirmedFunds" = "Витрачати непідтверджені кошти"
"functionUnavailableSync" = "Функція доступна лише після синхронізації"

// Receive page extras
"receivingAddress" = "Адреса для отримання"
"newAddress" = "Нова адреса"
"shareAddress" = "Поділитися адресою"
"copyAddress" = "Копіювати адресу"
"addressVerified" = "Адресу перевірено"

// Transactions list
"recent" = "Останні"
"viewAll" = "Показати всі"
"viewLink" = "Переглянути %s"
"viewDetails" = "Деталі"
"txStatusPending" = "%d з %d підтверджень"
"txStatusComplete" = "Підтверджено"
"txTypeRegular" = "Звичайна"
"txTypeMixed" = "Змішана"
"none" = "Немає"
"date" = "Дата"
"hash" = "Хеш"
"txID" = "ID транзакції"
"blockHeight" = "Висота блоку"
"size" = "Розмір"
"amountTotal" = "Загальна сума"
"sentFrom" = "Надіслано з"
"sentTo" = "Надіслано на"
"selfTransfer" = "Внутрішній переказ"
"viewOnExplorer" = "Переглянути в експлорері"

// Wallet management
"renameWallet" = "Перейменувати гаманець"
"renameWalletSheetTitle" = "Перейменувати гаманець"
"newWalletName" = "Нова назва гаманця"
"deleteWallet" = "Видалити гаманець"
"walletDeleted" = "Гаманець видалено"
"areYouSure" = "Ви впевнені?"
"confirmDelete" = "Підтвердити видалення"
"thisActionIsIrreversible" = "Цю дію неможливо скасувати"
"backupRequired" = "Спочатку зробіть резервну копію сід-фрази"
"backupYourSeed" = "Збережіть свою сід-фразу"
"writeDownSeed" = "Запишіть сід-фразу та зберігайте у безпечному місці"
"copySeed" = "Копіювати сід-фразу"
"seedHidden" = "Сід-фразу приховано"
"clickToReveal" = "Клацніть, щоб показати"

// Settings rows + groups
"debug" = "Налагодження"
"network" = "Мережа"
"txNotification" = "Сповіщення про транзакції"
"appLog" = "Журнал додатку"
"logLevel" = "Рівень журналу"
"logLevelInfo" = "Info"
"logLevelDebug" = "Debug"
"logLevelTrace" = "Trace"
"logLevelWarn" = "Warning"
"logLevelError" = "Error"
"logLevelCritical" = "Critical"
"viewLog" = "Переглянути журнал"
"appVersion" = "Версія додатку"
"buildDate" = "Дата збірки"
"build" = "Збірка"
"checkForUpdate" = "Перевірити оновлення"
"changeStartupPassword" = "Змінити пароль запуску"
"startupPassword" = "Пароль запуску"
"setStartupPassword" = "Встановити пароль запуску"
"removeStartupPassword" = "Видалити пароль запуску"
"switchToTestnet" = "Переключитися на Testnet"
"switchToMainnet" = "Переключитися на Mainnet"
"appRestartToApply" = "Додаток перезапуститься, щоб застосувати зміну. Продовжити?"
"dateAtTime" = "%s о %s"
"unsupportedWallet" = "(непідтримуваний гаманець: %s)"
"balanceError" = "помилка балансу: %v"

// Modals / common buttons
"create" = "Створити"
"restore" = "Відновити"
"import" = "Імпортувати"
"export" = "Експортувати"
"submit" = "Надіслати"
"start" = "Старт"
"stop" = "Стоп"
"retry" = "Повторити"
"refresh" = "Оновити"
"openAnyway" = "Відкрити все одно"
"copySuccess" = "Скопійовано в буфер"
"clear" = "Очистити"
"reset" = "Скинути"
"apply" = "Застосувати"

// Onboarding intro slider titles + subtitles (these were missing — page
// stayed in English even after locale switch because the page builds
// onBoardingScreens by calling values.String at construction time.)
"multiWalletSupport" = "Багатовалютний гаманець"
"multiWalletSubtext" = "Надсилайте та отримуйте VAR і SKA у мережі Monetarium."
"crossPlatform" = "Кросплатформенність"
"crossPlatformSubtext" = "Працює на macOS, Windows і Linux з єдиного коду."
"integratedExchangeFunctionality" = "Інтегрована екосистема"
"integratedExchangeSubtext" = "Безпечне зберігання VAR (Варта) і SKA (Скарб) у єдиному додатку."

// Onboarding extras
"introductionPage1" = "Skarb — багатовалютний гаманець для мережі Monetarium."
"introductionPage2" = "Зберігайте і переказуйте VAR (Варта) і SKA (Скарб) активи."
"introductionPage3" = "Резервна копія сід-фрази дозволяє відновити гаманець на будь-якому пристрої."
"skip" = "Пропустити"
"chooseSetupType" = "Оберіть тип налаштування"
"recommended" = "Рекомендоване"
"advanced" = "Розширене"
"recommendedSettings" = "Рекомендовані налаштування"
"advancedSettings" = "Розширені налаштування"
"recommendedSettingsMsg" = "Використовувати найбільш поширені налаштування. Підходить для більшості користувачів."
"advancedSettingsMsg" = "Дозволяє налаштувати все самостійно. Підходить досвідченим користувачам."
"advancedModalBody" = "Розширені налаштування підвищують приватність, вимикаючи зовнішні API."
"recommendedModalBody" = "Звичайні налаштування — стандартний режим роботи."
"getStarted" = "Розпочати"
"addWallet" = "Додати гаманець"
"gotIt" = "Зрозуміло"
"skipWalletCreation" = "Пропустити створення гаманця"
"createANewWallet" = "Створити новий гаманець"
"importExistingWallet" = "Імпортувати наявний гаманець"
"selectWalletToOpen" = "Оберіть гаманець, щоб відкрити"
"restoreWallet" = "Відновити гаманець"
"importWatchingOnlyWallet" = "Імпортувати гаманець лише для перегляду"
"watchOnlyWallet" = "Гаманець лише для перегляду"
"newWallet" = "Новий гаманець"
"enterWalletName" = "Введіть назву гаманця"
"existingWalletName" = "Гаманець із такою назвою вже існує"
"spendingPassword" = "Пароль для витрат"
"confirmSpendingPassword" = "Підтвердьте пароль для витрат"
"newSpendingPassword" = "Новий пароль для витрат"
"currentSpendingPassword" = "Поточний пароль для витрат"
"enterSpendingPassword" = "Введіть пароль для витрат"
"spendingPasswordInfo" = "Пароль для витрат використовується для підтвердження транзакцій."
"passwordNotMatch" = "Паролі не збігаються."
"errPassEmpty" = "Пароль не може бути порожнім."
"closingWallet" = "Завершення роботи гаманців…"
"openingWallet" = "Відкриття гаманців…"
"unlock" = "Розблокувати"
"unlockWithPassword" = "Розблокувати паролем"
"exit" = "Вийти"
"integratedExchange" = "Інтегрований обмін"
"warningMigrate" = "Виявлено проблему з файлами даних від попередньої версії. Щоб її виправити, потрібно перемістити дані до нової бази. Зробити це зараз?"
"dataFileErrorTitle" = "Помилка файлу даних"
"dataFileErrorBody" = "Виявлено проблему з файлами даних від попередньої версії. Щоб її виправити, потрібно перестворити базу даних — для цього знадобиться знову ввести сід-фразу гаманця. Зробити це зараз?"
"lowStorageSpaceTitle" = "Мало вільного місця"
"lowStorageSpaceBody" = "На пристрої замало вільного місця для синхронізації гаманця. Потрібно близько %d МБ, доступно %d МБ."
"signMessage" = "Підписати повідомлення"
"signMessageInfo" = "Підпис повідомлення доводить, що адреса належить вам, без розкриття приватного ключа."
"verifyMessage" = "Перевірити повідомлення"
"verifyMessageInfo" = "Перевірте, що повідомлення дійсно підписане власником адреси."
"databaseType" = "Тип бази даних"
"rescanBlockchain" = "Повторне сканування блокчейну"
"rescan" = "Сканувати знову"
"rescanInfo" = "Повторне сканування може виправити помилки балансу. Це триває довго — буде проскановано весь блокчейн."
"rescanProgressNotification" = "Перевірити прогрес можна на сторінці огляду."
"rescanningHeaders" = "Сканування заголовків · %v%%"
"rescanningBlocks" = "Сканування блоків"
"setGapLimit" = "Задати gap-ліміт"
"gapLimit" = "Gap-ліміт"
"setGapLimitInfo" = "%v У рідкісних випадках адреса може не виявлятись зі стандартним gap-лімітом 20. Використовуйте цю функцію лише після інших варіантів. Значення понад 100 істотно сповільнить роботу. %v"
"gapLimitInputErr" = "Невірне значення: дозволено від 1 до 1000."
"viewStats" = "Переглянути статистику"
"dangerZone" = "Небезпечна зона"
"wipeNetworkState" = "Очистити стан мережі"
"wipeNetworkStateBody" = "Це повністю видалить локальний datadir мережі %s (заголовки блоків, кеш пірів, всі гаманці цієї мережі та їхні бази даних). Додаток закриється; запустіть його знову, щоб почати з нуля та відновити гаманці із сід-фрази.\n\nПереконайтеся, що сід-фрази всіх гаманців цієї мережі збережені. Відмінити дію неможливо."
"removeWallet" = "Видалити гаманець з пристрою"
"removeWalletInfo" = "%v Дійсно видалити %v %s%v? Введіть назву гаманця нижче для підтвердження. %v"
"noValidWalletFound" = "Гаманців ще немає"
"createOrRestoreToSeeBalances" = "Створіть або відновіть гаманець Monetarium, щоб побачити баланси VAR і SKA."
"amountReceived" = "Отримано %s %s"
"changeSpendingPass" = "Змінити пароль для витрат"
"setupStartupPassword" = "Налаштувати стартовий пароль"
"startupPasswordEnabled" = "Стартовий пароль увімкнено"
"startupPasswordInfo" = "Стартовий пароль захищає доступ до самого додатка."
"changeWalletName" = "Змінити назву гаманця"
"changeSpecificPeer" = "Змінити піра"
"removePeer" = "Видалити піра"
"userAgent" = "User-Agent"
"changeUserAgent" = "Змінити User-Agent"
"removeUserAgent" = "Видалити User-Agent"
"notifications" = "Сповіщення"
"help" = "Довідка"
"peers" = "Піри"
"beepForNewBlocks" = "Звук на нові блоки"
"viewAppLog" = "Переглянути журнал додатка"
"walletLog" = "Журнал гаманця"
"statistics" = "Статистика"
"bestBlockAge" = "Вік останнього блоку"
"bestBlockTimestamp" = "Час останнього блоку"
"connectedPeersCount" = "Підключених пірів"
"noConnectedPeer" = "Немає підключених пірів"
"walletDirectory" = "Папка гаманця"
"walletStatus" = "Статус гаманця"
"walletSyncing" = "Синхронізація гаманця"
"walletNotSynced" = "Гаманець не синхронізовано"
"connection" = "З'єднання"
"notConnected" = "Не підключено"
"syncingProgress" = "Прогрес синхронізації"
"syncingState" = "Стан синхронізації"
"disconnect" = "Відключити"
"reconnect" = "Перепідключити"
"hideDetails" = "Сховати деталі"

// Asset & balance display
"VAR" = "VAR"
"SKA" = "SKA"
"asset" = "Актив"
"expectedAsset" = "Очікуваний актив"
"allAssets" = "Усі активи"

// Wallet sync states (extras)
"connecting2" = "Підключення до пірів…"
"fetchingHeaders" = "Отримання заголовків блоків…"
"discoveringAddresses" = "Пошук адрес…"
"rescanning" = "Повторне сканування…"
"finalising" = "Завершення…"

// Bulk translation batch — 212 keys that were live-referenced from Go code
// but missing from this file (fell back to English). Sorted by feature area;
// strings carry %d / %v / %s placeholders identical to en.go.

// Accounts & wallet management
"accountList" = "Список акаунтів"
"acctCreated" = "Акаунт створено"
"acctDetailsKey" = "%d зовнішніх, %d внутрішніх, %d імпортованих"
"acctName" = "Назва акаунта"
"acctNum" = "Номер акаунта"
"acctRenamed" = "Акаунт перейменовано"
"addAcctWarn" = "%v Акаунти %v не можна %v видалити після створення.%v"
"addNewAccount" = "Додати акаунт"
"addrNotOwned" = "Адреса не належить жодному гаманцю"
"addressCopied" = "Адресу скопійовано"
"addressDiscoveryStartedBody" = "Перегляньте сторінку інформації гаманця для прогресу"
"allWallets" = "Усі гаманці"
"backToWallets" = "Назад до гаманців"
"createNewAccount" = "Створити акаунт"
"noValidAccountFound" = "Валідний акаунт не знайдено"
"rename" = "Перейменувати"
"renameAcct" = "Перейменувати акаунт"
"walletExist" = "Гаманець з назвою %s вже існує"
"walletNameMismatch" = "Введена назва гаманця не збігається з вибраною"
"walletRemoved" = "Гаманець видалено"
"walletRenamed" = "Гаманець успішно перейменовано"
"walletsCreationLimitBody" = "Досягнуто ліміту створення гаманців"
"walletsCreationLimitTitle" = "Ліміт гаманців"
"xpubWalletExist" = "Гаманець з ідентичним розширеним публічним ключем вже існує."
"seedAlreadyExist" = "Гаманець з ідентичним сідом вже існує."
"walletNameLengthError" = "Назва гаманця не може бути довшою за 32 символи."

// Seed backup / restore
"askedEnterSeedWords" = "На наступному екрані буде запропоновано ввести сід-фразу."
"imawareOfRisk" = "Я обізнаний з ризиками"
"backupInfo" = "%v Без резервної копії — без коштів! %v Щоб не втратити кошти при втраті або поломці пристрою, зробіть резервну копію гаманця %v зараз %v та зберігайте її в %v безпечному місці! %v"
"backupLater" = "Резервна копія пізніше"
"backupNow" = "Зробити резервну копію"
"backupWarning" = "Потрібна резервна копія гаманця"
"importantSeedPhrase" = "Сід-фраза НАДЗВИЧАЙНО ВАЖЛИВА."
"hideSeedPhrase" = "Будь-хто з вашою сід-фразою може викрасти ваші кошти. НЕ показуйте її нікому."
"viewSeedPhrase" = "Переглянути сід-фразу"
"writeDownAllXWords" = "Запишіть усі %d слів у правильному порядку."
"wroteAllWords" = "Я записав усі %d слів"
"selectPhrasesToVerify" = "Виберіть правильні фрази для підтвердження."
"seedPhraseVerified" = "Резервну копію сід-фрази підтверджено"
"seedValidationFailed" = "Не вдалось підтвердити. Перевірте кожне слово сіду і спробуйте знову."
"seedWords" = "Слова сід-фрази"
"yourSeedWords" = "Ваші слова сід-фрази"
"sureToExitBackup" = "Дійсно вийти з процесу резервного копіювання сіду?"
"confirmShowSeed" = "Підтвердьте показ сіду"
"confirmToVerifySeed" = "Підтвердити перевірку сіду"
"invalidSeedPhrase" = "Невірна сід-фраза"
"pasteSeedWords" = "Вставити слова сіду"
"enterWalletSeed" = "Введіть сід гаманця"
"enterWalletHex" = "Введіть Hex гаманця"
"inputSeed" = "Введіть сід"
"validateWalSeed" = "Перевірити сід гаманця"
"validateWalHex" = "Перевірити Hex гаманця"
"invalidHex" = "Невірний hex"
"hex" = "Hex"
"exportWalletSeed" = "Експортувати сід гаманця"
"notBackedUp" = "Потрібна резервна копія"

// Passwords / spending password / startup password
"confirmNewSpendingPassword" = "Підтвердьте новий пароль для витрат"
"confirmNewStartupPass" = "Підтвердьте новий стартовий пароль"
"confirmRemoveStartupPass" = "Підтвердьте вимкнення стартового пароля"
"confirmStartupPass" = "Підтвердьте поточний стартовий пароль"
"createStartupPassword" = "Створити стартовий пароль"
"currentStartupPass" = "Поточний стартовий пароль"
"newStartupPass" = "Новий стартовий пароль"
"spendingPasswordInfo2" = "Цей пароль для витрат — лише для нового гаманця"
"spendingPasswordUpdated" = "Пароль для витрат оновлено"
"startupPassConfirm" = "Стартовий пароль змінено"
"inputPassword" = "Введіть пароль"
"hint" = "Підказка"

// Transactions / details / lists
"confStatus" = "Статус підтвердження"
"confirmations" = "Підтверджень"
"confirmed" = "Підтверджено"
"confirmPending" = "Потрібне підтвердження"
"confirmToRemove" = "Підтвердьте видалення"
"confirmToSign" = "Підтвердьте підписання"
"direction" = "Напрямок"
"includedInBlock" = "Включено в блок"
"missedOn" = "Пропущено"
"nConfirmations" = "%d підтверджень"
"note" = "Нотатка"
"pending" = "В очікуванні"
"recipient" = "Отримувач"
"republished" = "Непідтверджені транзакції повторно опубліковано в мережі %s"
"rescanInvalid" = "Уже відбувається інша синхронізація. Повторне сканування неможливе."
"sendConfModalTitle" = "Ви збираєтесь надіслати"
"sendInfo" = "Введіть або відскануйте адресу гаманця-отримувача та суму для надсилання."
"selectedUTXO" = "Вибране UTXO"
"summary" = "Підсумок"
"status" = "Статус"
"to" = "Кому"
"from" = "Від"
"totalAmount" = "Загальна сума"
"transactionID" = "ID транзакції"
"txFee" = "Комісія транзакції"
"txHashCopied" = "Хеш транзакції скопійовано"
"txOverview" = "Огляд транзакцій"
"txRegular" = "Звичайні транзакції"
"txSent" = "Транзакцію надіслано!"
"txSize" = "Розмір транзакції%v"
"txdetailsInfo" = "Деталі транзакції"
"type" = "Тип"
"umined" = "Непідтверджено"
"xInputsConsumed" = "Спожито входів: %d"
"xOutputCreated" = "Створено виходів: %d"
"noUTXOs" = "UTXO недоступні"
"descriptionNote" = "Нотатка з описом"
"destAddr" = "Адреса призначення"
"destination" = "Призначення"
"destinationLabelAddress" = "Адреса призначення"
"destinationLabelWallet" = "Гаманець призначення"
"destinationLabelAccount" = "Акаунт призначення"
"destinationWallet" = "Гаманець-отримувач"
"exportTransaction" = "Експортувати транзакцію"
"exportTransactionSuccessMsg" = "Транзакції успішно експортовано та збережено в %s."
"exportTransactionsMsg" = "Експортувати транзакції з гаманців. Процес виконуватиметься у фоні; коли все буде готово, ви отримаєте сповіщення."
"includedInBlock" = "Включено в блок"
"cost" = "Вартість%v"
"priority" = "Пріоритет%v"
"fetched" = "Завантажено"
"fetchingBlockHeaders" = "Отримання заголовків блоків"

// Sync / network state
"canceling" = "Скасування…"
"connectNetworkFailed" = "Підключення до мережі блокчейну недоступне."
"sync" = "Синхронізація"
"syncCompTime" = "Орієнтовний час завершення синхронізації"
"syncSteps" = "Крок %d/%d"
"syncingProgressStat" = "%s відставання"
"timeLeftFmt" = "%v залишилось"
"peer" = "Пір"
"removePeerWarn" = "Дійсно видалити цей пір?"
"keepAppOpen" = "Тримайте додаток відкритим"
"keepInMind" = "Майте на увазі"

// Address / sign / verify
"copyLink" = "Скопіюйте та вставте посилання в браузер."
"clearAll" = "Очистити все"
"clearSelection" = "Очистити вибір"
"colon" = ": "
"emptyMsg" = "Поле не може бути порожнім. Введіть валідне підписане повідомлення."
"emptySign" = "Поле не може бути порожнім. Введіть валідний підпис."
"enterAddressToSign" = "Введіть адресу та повідомлення для підписання:"
"enterValidAddress" = "Введіть валідну адресу"
"enterValidMsg" = "Введіть валідне повідомлення для підписання"
"enterWalDetails" = "Введіть дані гаманця"
"extendedCopied" = "Розширений ключ скопійовано"
"extendedInfo" = "Розширений публічний ключ використовується для імпорту гаманця як watch-only"
"extendedKey" = "Розширений публічний ключ"
"extendedPubKey" = "Розширений публічний ключ"
"enterExtendedPubKey" = "Введіть розширений публічний ключ"
"howToCopy" = "Як скопіювати"
"invalidSignature" = "Невірний підпис або повідомлення"
"key" = "Ключ"
"message" = "Повідомлення"
"notOwned" = "Валідна адреса, але вам не належить."
"owned" = "Валідна адреса, що належить вам."
"paste" = "Вставити"
"securityTools" = "Інструменти безпеки"
"securityToolsInfo" = "%v Тут будуть розташовані різноманітні інструменти для безпеки криптовалюти. %v"
"signCopied" = "Підпис скопійовано"
"signature" = "Підпис"
"validate" = "Перевірити"
"validateAddr" = "Перевірити адресу"
"validateHostErr" = "%s не є валідною IP-адресою або URL"
"validateMsg" = "Перевірити адресу"
"validateNote" = "Введіть адресу для перевірки:"
"validSignature" = "Підпис валідний"
"verify" = "Перевірити"
"verifyMsgNote" = "Введіть адресу, підпис і повідомлення для перевірки:"
"xpubKeyErr" = "Помилка перевірки xpub: %v"

// Settings / network / API
"exchangeAPI" = "API курсу обміну"
"exchangeRate" = "Отримувати курс обміну"
"governanceAPI" = "API управління"
"updateAPI" = "API перевірки оновлень"
"fetchRateWarningTitle" = "Попередження налаштувань"
"notAllowed" = "API %s не дозволено поточними налаштуваннями мережі."
"notAvailable" = "Недоступно"
"privacyInfo" = "%v При активації змішувача кошти поступово переказуватимуться з немікшованого акаунта на мікшований. %v Важливо: тримайте додаток відкритим, поки змішувач працює. %v Процедура автоматично зупиниться, коли немікшований баланс буде повністю змішано.%v"
"privacyModeActive" = "(Приватність мережі увімкнено)"
"privacyModeInfo" = "Інформація про приватність мережі"
"privacyModeInfoDesc" = "Коли увімкнено, всі HTTP API-виклики вимкнено, окрім Network Check API, який перевіряє доступ до інтернету."
"privacySettings" = "Приватність мережі"
"selectAServer" = "Виберіть сервер"
"selectAssetType" = "Виберіть тип активу"
"sourceModalInfo" = "Гаманці, які не завершили синхронізацію, не відображатимуться. %v Відшкодування й залишки повертатимуться на вибраний акаунт-джерело."
"webURL" = "Веб-URL"
"website" = "Вебсайт"
"telegram" = "Telegram"
"twitter" = "Twitter"
"matrix" = "Matrix"
"documentation" = "Документація"
"helpInfo" = "Для додаткової інформації про Skarb відвідайте документацію Monetarium."
"iPAddress" = "IP-адреса"
"rateBinanceWarning" = "*У деяких країнах Binance заблоковано — отримання курсу може не працювати."
"rateKucoinWarning" = "*У деяких країнах Kucoin заблоковано — отримання курсу може не працювати."
"usdBinance" = "USD (Binance)"
"usdBinanceUS" = "USD (Binance US)"
"usdCoinpaprika" = "USD (Coinpaprika)"
"usdKucoin" = "USD (Kucoin)"
"usdMessari" = "USD (Messari)"

// Misc generic
"dateCreated" = "Дата створення"
"dateSize" = "Дані гаманця"
"days" = "Днів"
"hours" = "Годин"
"minutes" = "Хвилин"
"seconds" = "Секунд"
"time" = "Час"
"yesterday" = "Вчора"
"disabled" = "вимкнено"
"enabled" = "увімкнено"
"discoverAddressUsage" = "Виявити використання адрес"
"external" = "Зовнішній"
"oK" = "OK"
"receiveInfo" = "Для конфіденційності кожного разу при отриманні платежу генерується нова адреса."
"removeRecipientWarning" = "Дійсно видалити отримувача?"
"remove" = "Видалити"
"reward" = "Винагорода"
"revocation" = "Відкликання"
"immature" = "Не дозріле"
"immatureInfo" = "Дозріє через %v із %v блоків (%v)"
"lifeSpan" = "Тривалість життя"
"live" = "Активне"
"mixed" = "Змішане"
"mixingNotSetUp" = "Налаштуйте змішувач у вкладці StakeShuffle, щоб вимкнути."
"purchasedOn" = "Куплено"
"expiredOn" = "Завершилось"
"step1" = "Крок 1/2"
"step2of2" = "Крок 2/2"
"uptime" = "Час безперервної роботи"
"willMigrate" = "Буде мігровано"
"migrateNow" = "Мігрувати"
"migrateWallet" = "Мігрувати гаманець"
"doNotMigrate" = "Зробити пізніше!"
"license" = "Ліцензія"
"hDPath" = "HD-шлях"
"word" = "Слово"
"wordSeedType" = "Тип сід-фрази:"
"totalValueMsg" = "Загальна вартість — це оцінка всіх ваших гаманців за ринковим курсом USD.%v Загальний баланс може бути неактуальним через гаманці, які не повністю синхронізовані. Для точнішого балансу перейдіть на сторінку конкретного гаманця. %v Увімкнути/вимкнути отримання курсу можна в налаштуваннях додатка."
"confirmUmixedSpending" = "Підтвердити витрачання з немікшованих акаунтів"
"allowSpendingFromUnmixedAccount" = "Дозволити витрачання з немікшованих акаунтів"
"allowUnspendUnmixedAcct" = "Заборонити витрачання з немікшованих акаунтів"
"restrictedDetail" = "Обмежено"

// Removed-feature strings (staking, DEX, mixer, voting/governance). Stubs
// for these features still live in the codebase (libwallet/phase1_stubs.go,
// account_mixer_stub.go) and a handful of error/info paths can still
// surface them; translate so a Ukrainian-locale user doesn't see English
// fallback if a stub fires. Strings preserve the upstream "DCR" / "VSP"
// terminology — those are protocol-level names, not brand surfaces.

// DEX (stub)
"activeDexOrderError" = "Існує активне DEX-замовлення. Дійсно завершити роботу?"
"backupDEXSeed" = "Резервна копія DEX-сіду"
"dEX" = "DEX"
"dEXResetSuccessful" = "Дані DEX очищено"
"dEXSeed" = "DEX-сід"
"dexError" = "Помилка DCRDEX"
"dexPassword" = "Пароль DCRDEX"
"resetDEXData" = "Очистити дані DEX"
"resetDEXDataWarning" = "Це видалить базу DEX, включно з інформацією про активні бонди та підключені DEX-сервери. Переконайтесь, що маєте резервну копію DEX-сіду."
"updateDEXWalletPasswordReason" = "Ваш гаманець %s (%s) підключений до акаунту DEX. Введіть пароль DEX для оновлення зв'язаного гаманця."
"bondStrengthMsg" = "Кількість бондів, які ви хочете розмістити зараз.%vПримітка: бонди вірності — це кошти із замком часу, які можна забрати лише в майбутньому. Призначені для запобігання деструктивній поведінці на кшталт відмови від обмінів.%vЧим більше бондів, тим вищий ваш ліміт торгівлі."

// Mixer (stub)
"mixerRunning" = "Змішувач працює..."
"setupMixerInfo" = "%v Для роботи змішувача буде створено два спеціальні акаунти: %v змішаний %v і %v незмішаний %v. %v Скасувати неможливо.%v"
"useMixer" = "Як користуватися змішувачем?"
"unmixedBalance" = "Незмішаний баланс"

// Staking / voting (stub)
"expired" = "Прострочено"
"feeRateAPI" = "API ставок комісій"
"feeRates" = "Ставки комісій"
"liveInfoDisc" = "активний %v днів (%v з %v залишилось)"
"lockedByTickets" = "Заблоковано тикетами"
"missedTickets" = "Пропущений тикет"
"revoke" = "Відкликати"
"revokeCause" = "Причина відкликання"
"revoked" = "Відкликано"
"stakingActivity" = "Активність стейкінгу"
"stakingTx" = "Транзакції стейкінгу"
"ticket" = "Тикет"
"ticketDetails" = "Деталі тикета"
"ticketPrice" = "Ціна тикета"
"ticketRevoked" = "Тикет відкликано"
"ticketVoted" = "Тикет проголосував\nВинагорода за голос: %s DCR"
"vote" = "Голосувати"
"votedOn" = "Проголосовано"
"voted" = "Проголосовано"
"votes" = "%d голосів"
"votingAuthority" = "Право голосу"
"voteTooltip" = "%d %% позитивних голосів потрібно для затвердження"
"voteStartedNotif" = "Голосування розпочато по пропозиції з токеном: %s"
"voteEndedNotif" = "Голосування завершено по пропозиції з токеном: %s"
"newProposalUpdate" = "Нове оновлення пропозиції з токеном: %s"
"proposalAddedNotif" = "Додано нову пропозицію. Назва: %s"
"vsp" = "VSP"
"vspFee" = "Комісія VSP"
"vSPAPI" = "API VSP"

// Misc (still in active flows)
"howNotToStoreSeedPhrase" = "Категорично не рекомендується зберігати сід-фразу в цифровому вигляді (наприклад, скриншот)."
"howToStoreSeedPhrase" = "Рекомендується зберігати сід-фразу у фізичній формі (наприклад, записати на папері)."
"seedPhraseToRestore" = "сід-фраза — єдиний спосіб відновити гаманець."
"sureToSafeStoreSeed" = "Переконайтесь, що резервна копія сід-фрази зберігається в безпечному місці."
"rebroadcast" = "Повторно опублікувати"
"walletRestoreMsg" = "Цей гаманець можна відновити з сід-фрази після видалення."
"walletRestored" = "Гаманець відновлено"
"multiWalletSupportSubtext" = "Один додаток для всіх ваших активів Monetarium."

// Custom-fee feature (send page advanced options). Strings use "за КБ"
// (per KB) and rely on FormatTxAmountBig to embed the coin symbol — the
// %s placeholders arrive pre-formatted as "X.YZ SKA1" / "X.YZ VAR",
// so the template doesn't repeat the unit.
"customFeeTitle" = "Власна комісія"
"feeRatePerKbHint" = "Ставка комісії за КБ"
"feeRateBounds" = "Діапазон: %s — %s за КБ"
"apply" = "Застосувати"
"customFeeApplied" = "Ставку застосовано: %s за КБ. Орієнтовна комісія: %s (≈ ставка × розмір tx)"
"customFeeCleared" = "Комісію скинуто (буде використано стандартну ставку мережі)"
"feeRateBelowMin" = "Ставка %s нижче мінімуму мережі (%s за КБ)"
"feeRateAboveMax" = "Ставка %s вище допустимого максимуму (%s за КБ)"
"feeRateNotSupported" = "Власну комісію не підтримує цей тип монети"
`
