package localizable

const UKRAINIAN = "uk"

// Ukrainian translation. Covers the most user-visible strings (navigation,
// send/receive/transactions, balances, settings, common errors). Missing keys
// fall back to the English file via values.String's per-language fallback.
const UK = `
"appName" = "Skarb"
"appTitle" = "Skarb Wallet (%s)"
"appWallet" = "Skarb Wallet"
"welcomeNote" = "Ласкаво просимо до Skarb — гаманця мережі Monetarium."

// Navigation
"home" = "Головна"
"overview" = "Огляд"
"send" = "Надіслати"
"receive" = "Отримати"
"transactions" = "Транзакції"
"settings" = "Налаштування"
"info" = "Інформація"
"accounts" = "Акаунти"
"account" = "Акаунт"
"wallets" = "Гаманці"
"wallet" = "Гаманець"
"createNewWallet" = "Створити новий гаманець"
"restoreExistingWallet" = "Відновити наявний гаманець"
"importWallet" = "Імпортувати гаманець"
"selectWallet" = "Оберіть гаманець"

// Common UI
"all" = "Усі"
"cancel" = "Скасувати"
"save" = "Зберегти"
"confirm" = "Підтвердити"
"continue" = "Продовжити"
"next" = "Далі"
"back" = "Назад"
"done" = "Готово"
"ok" = "Гаразд"
"yes" = "Так"
"no" = "Ні"
"close" = "Закрити"
"delete" = "Видалити"
"edit" = "Редагувати"
"copy" = "Копіювати"
"copied" = "Скопійовано"
"loading" = "Завантаження…"
"search" = "Пошук"
"filter" = "Фільтр"

// Balances
"balance" = "Баланс"
"totalBalance" = "Загальний баланс"
"labelSpendable" = "Доступний"
"unconfirmed" = "Непідтверджено"
"locked" = "Заблоковано"
"watchOnly" = "Лише перегляд"

// Send page
"amount" = "Сума"
"address" = "Адреса"
"destinationAddress" = "Адреса отримувача"
"sourceAccount" = "Акаунт-джерело"
"sourceWallet" = "Гаманець-джерело"
"fee" = "Комісія"
"feeRate" = "Ставка комісії"
"totalCost" = "Загальна сума"
"balanceAfterSend" = "Баланс після відправлення"
"balanceAfter" = "Баланс після відправлення"
"destinationMissing" = "Адреса отримувача не вказана"
"sameAddressReceivesHint" = "Адреса однакова для всіх активів. Попросіть відправника надіслати саме %s."
"myAddress" = "Моя адреса"
"nextAddress" = "Нова адреса"
"sendMax" = "Надіслати все"
"signAndSend" = "Підписати та надіслати"
"addRecipient" = "Додати отримувача"
"removeRecipient" = "Прибрати отримувача"
"invalidAmount" = "Некоректна сума"
"invalidAddress" = "Некоректна адреса"
"insufficientFund" = "Недостатньо коштів"

// Receive page
"yourAddress" = "Ваша адреса"
"generateNewAddress" = "Згенерувати нову адресу"
"warningWatchWallet" = "Увага: це гаманець лише для перегляду — отримання можливе, відправлення ні."

// Transactions
"recentTransactions" = "Останні транзакції"
"noTransactions" = "Транзакцій ще немає"
"transactionDetails" = "Деталі транзакції"
"sent" = "Надіслано"
"received" = "Отримано"
"transferred" = "Переказано"
"complete" = "Завершено"
"unconfirmedTx" = "Непідтверджено"
"newest" = "Найновіші"
"oldest" = "Найстаріші"

// Settings
"general" = "Загальні"
"language" = "Мова"
"english" = "English"
"ukrainian" = "Українська"
"french" = "French"
"spanish" = "Spanish"
"chinese" = "Chinese"
"darkMode" = "Темна тема"
"currency" = "Валюта"
"currencyConversion" = "Конвертація валют"
"about" = "Про програму"
"version" = "Версія"
"security" = "Безпека"
"changeSpendingPassword" = "Змінити пароль на витрачання"
"backupSeed" = "Резервна копія сід-фрази"
"viewSeed" = "Переглянути сід-фразу"
"verifySeed" = "Перевірити сід-фразу"

// Sync
"connecting" = "Підключення…"
"syncing" = "Синхронізація…"
"synced" = "Синхронізовано"
"notSynced" = "Не синхронізовано"
"startSync" = "Почати синхронізацію"
"stopSync" = "Зупинити синхронізацію"
"online" = "Онлайн, "
"offline" = "Офлайн, "
"connectedToPeers" = "Підключено до пірів: %d"

// Onboarding
"selectLanguage" = "Оберіть мову"
"selectNetwork" = "Оберіть мережу"
"mainnet" = "Mainnet"
"testnet" = "Testnet"
"createWallet" = "Створити гаманець"
"walletName" = "Назва гаманця"
"setSpendingPassword" = "Встановіть пароль на витрачання"
"confirmPassword" = "Підтвердіть пароль"
"passwordMismatch" = "Паролі не співпадають"
"passwordTooShort" = "Пароль закороткий"

// Errors
"error" = "Помилка"
"warning" = "Увага"
"unknown" = "Невідомо"
"failed" = "Не вдалося"
"tryAgain" = "Спробувати ще раз"
"invalidPassphrase" = "Неправильний пароль"
"insufficientFunds" = "Недостатньо коштів"
"walletNotLoaded" = "Гаманець не завантажено"
"syncAlreadyInProgress" = "Синхронізація вже триває"
"functionUnavailable" = "Функція недоступна"
"noInternet" = "Немає підключення до інтернету"

// Sync info
"blockHeaderFetched" = "Заголовків блоків отримано"
"blockHeaderFetchedCount" = "%d з %d"
"bestBlocks" = "Найкращий блок"
"blocksLeft" = "Залишилось блоків"
"blocksScanned" = "Відскановано блоків"
"addressDiscovering" = "Пошук адрес"
"addressDiscoveryStarted" = "Розпочато пошук адрес"
"addressDiscoveryInProgress" = "Триває пошук адрес"
"rescanProgress" = "Прогрес повторного сканування"
"syncProgressTitle" = "Прогрес синхронізації"
"latestBlock" = "Останній блок"
"connectedTo" = "Підключено до %d пірів"
"peersConnected" = "Підключені піри"
"connectToSpecificPeer" = "Підключатися до конкретного піра"
"viewSyncDetails" = "Деталі синхронізації"

// Send page details
"max" = "Макс"
"automatic" = "Автоматичний"
"manual" = "Ручний"
"coinSelection" = "Вибір UTXO"
"advancedOptions" = "Розширені налаштування"
"description" = "Опис"
"txDescriptionTitle" = "Опис транзакції (необовʼязково)"
"transactionFee" = "Комісія за транзакцію"
"signTransaction" = "Підписати транзакцію"
"reviewTransaction" = "Перевірте транзакцію"
"transactionConfirmed" = "Транзакцію підтверджено"
"broadcasting" = "Розсилання…"
"broadcastingTransaction" = "Розсилання транзакції"
"transactionSent" = "Транзакцію надіслано"
"unconfirmedFunds" = "Витрачати непідтверджені кошти"
"functionUnavailableSync" = "Функція доступна лише після синхронізації"

// Receive page extras
"receivingAddress" = "Адреса для отримання"
"newAddress" = "Нова адреса"
"shareAddress" = "Поділитися адресою"
"copyAddress" = "Копіювати адресу"
"addressVerified" = "Адресу перевірено"

// Transactions list
"recent" = "Останні"
"viewAll" = "Показати всі"
"viewDetails" = "Деталі"
"txStatusPending" = "%d з %d підтверджень"
"txStatusComplete" = "Підтверджено"
"txTypeRegular" = "Звичайна"
"txTypeMixed" = "Змішана"
"none" = "Немає"
"date" = "Дата"
"hash" = "Хеш"
"txID" = "ID транзакції"
"blockHeight" = "Висота блоку"
"size" = "Розмір"
"amountTotal" = "Загальна сума"
"sentFrom" = "Надіслано з"
"sentTo" = "Надіслано на"
"selfTransfer" = "Внутрішній переказ"
"viewOnExplorer" = "Переглянути в експлорері"

// Wallet management
"renameWallet" = "Перейменувати гаманець"
"renameWalletSheetTitle" = "Перейменувати гаманець"
"newWalletName" = "Нова назва гаманця"
"deleteWallet" = "Видалити гаманець"
"walletDeleted" = "Гаманець видалено"
"areYouSure" = "Ви впевнені?"
"confirmDelete" = "Підтвердити видалення"
"thisActionIsIrreversible" = "Цю дію неможливо скасувати"
"backupRequired" = "Спочатку зробіть резервну копію сід-фрази"
"backupYourSeed" = "Збережіть свою сід-фразу"
"writeDownSeed" = "Запишіть сід-фразу та зберігайте у безпечному місці"
"copySeed" = "Копіювати сід-фразу"
"seedHidden" = "Сід-фразу приховано"
"clickToReveal" = "Клацніть, щоб показати"

// Settings rows + groups
"debug" = "Налагодження"
"network" = "Мережа"
"txNotification" = "Сповіщення про транзакції"
"appLog" = "Журнал додатку"
"logLevel" = "Рівень журналу"
"logLevelInfo" = "Info"
"logLevelDebug" = "Debug"
"logLevelTrace" = "Trace"
"logLevelWarn" = "Warning"
"logLevelError" = "Error"
"logLevelCritical" = "Critical"
"viewLog" = "Переглянути журнал"
"appVersion" = "Версія додатку"
"buildDate" = "Дата збірки"
"build" = "Збірка"
"checkForUpdate" = "Перевірити оновлення"
"changeStartupPassword" = "Змінити пароль запуску"
"startupPassword" = "Пароль запуску"
"setStartupPassword" = "Встановити пароль запуску"
"removeStartupPassword" = "Видалити пароль запуску"
"switchToTestnet" = "Переключитися на Testnet"
"switchToMainnet" = "Переключитися на Mainnet"

// Modals / common buttons
"create" = "Створити"
"restore" = "Відновити"
"import" = "Імпортувати"
"export" = "Експортувати"
"submit" = "Надіслати"
"start" = "Старт"
"stop" = "Стоп"
"retry" = "Повторити"
"refresh" = "Оновити"
"openAnyway" = "Відкрити все одно"
"copySuccess" = "Скопійовано в буфер"
"clear" = "Очистити"
"reset" = "Скинути"
"apply" = "Застосувати"

// Onboarding intro slider titles + subtitles (these were missing — page
// stayed in English even after locale switch because the page builds
// onBoardingScreens by calling values.String at construction time.)
"multiWalletSupport" = "Багатовалютний гаманець"
"multiWalletSubtext" = "Надсилайте та отримуйте VAR і SKA у мережі Monetarium."
"crossPlatform" = "Кросплатформенність"
"crossPlatformSubtext" = "Працює на macOS, Windows і Linux з єдиного коду."
"integratedExchangeFunctionality" = "Інтегрована екосистема"
"integratedExchangeSubtext" = "Безпечне зберігання VAR (Варта) і SKA (Скарб) у єдиному додатку."

// Onboarding extras
"introductionPage1" = "Skarb — багатовалютний гаманець для мережі Monetarium."
"introductionPage2" = "Зберігайте і переказуйте VAR (Варта) і SKA (Скарб) активи."
"introductionPage3" = "Резервна копія сід-фрази дозволяє відновити гаманець на будь-якому пристрої."
"skip" = "Пропустити"
"chooseSetupType" = "Оберіть тип налаштування"
"recommended" = "Рекомендоване"
"advanced" = "Розширене"
"recommendedSettings" = "Рекомендовані налаштування"
"advancedSettings" = "Розширені налаштування"
"recommendedSettingsMsg" = "Використовувати найбільш поширені налаштування. Підходить для більшості користувачів."
"advancedSettingsMsg" = "Дозволяє налаштувати все самостійно. Підходить досвідченим користувачам."
"advancedModalBody" = "Розширені налаштування підвищують приватність, вимикаючи зовнішні API."
"recommendedModalBody" = "Звичайні налаштування — стандартний режим роботи."
"getStarted" = "Розпочати"
"addWallet" = "Додати гаманець"
"gotIt" = "Зрозуміло"
"skipWalletCreation" = "Пропустити створення гаманця"
"createANewWallet" = "Створити новий гаманець"
"importExistingWallet" = "Імпортувати наявний гаманець"
"selectWalletToOpen" = "Оберіть гаманець, щоб відкрити"
"restoreWallet" = "Відновити гаманець"
"importWatchingOnlyWallet" = "Імпортувати гаманець лише для перегляду"
"watchOnlyWallet" = "Гаманець лише для перегляду"
"newWallet" = "Новий гаманець"
"enterWalletName" = "Введіть назву гаманця"
"existingWalletName" = "Гаманець із такою назвою вже існує"
"spendingPassword" = "Пароль для витрат"
"confirmSpendingPassword" = "Підтвердьте пароль для витрат"
"newSpendingPassword" = "Новий пароль для витрат"
"currentSpendingPassword" = "Поточний пароль для витрат"
"enterSpendingPassword" = "Введіть пароль для витрат"
"spendingPasswordInfo" = "Пароль для витрат використовується для підтвердження транзакцій."
"passwordNotMatch" = "Паролі не збігаються."
"errPassEmpty" = "Пароль не може бути порожнім."
"closingWallet" = "Завершення роботи гаманців…"
"openingWallet" = "Відкриття гаманців…"
"unlock" = "Розблокувати"
"unlockWithPassword" = "Розблокувати паролем"
"exit" = "Вийти"
"integratedExchange" = "Інтегрований обмін"
"warningMigrate" = "Виявлено проблему з файлами даних від попередньої версії. Щоб її виправити, потрібно перемістити дані до нової бази. Зробити це зараз?"
"dataFileErrorTitle" = "Помилка файлу даних"
"dataFileErrorBody" = "Виявлено проблему з файлами даних від попередньої версії. Щоб її виправити, потрібно перестворити базу даних — для цього знадобиться знову ввести сід-фразу гаманця. Зробити це зараз?"
"lowStorageSpaceTitle" = "Мало вільного місця"
"lowStorageSpaceBody" = "На пристрої замало вільного місця для синхронізації гаманця. Потрібно близько %d МБ, доступно %d МБ."
"signMessage" = "Підписати повідомлення"
"signMessageInfo" = "Підпис повідомлення доводить, що адреса належить вам, без розкриття приватного ключа."
"verifyMessage" = "Перевірити повідомлення"
"verifyMessageInfo" = "Перевірте, що повідомлення дійсно підписане власником адреси."
"databaseType" = "Тип бази даних"
"rescanBlockchain" = "Повторне сканування блокчейну"
"rescan" = "Сканувати знову"
"rescanInfo" = "Повторне сканування може виправити помилки балансу. Це триває довго — буде проскановано весь блокчейн."
"rescanProgressNotification" = "Перевірити прогрес можна на сторінці огляду."
"rescanningHeaders" = "Сканування заголовків · %v%%"
"rescanningBlocks" = "Сканування блоків"
"setGapLimit" = "Задати gap-ліміт"
"gapLimit" = "Gap-ліміт"
"setGapLimitInfo" = "%v У рідкісних випадках адреса може не виявлятись зі стандартним gap-лімітом 20. Використовуйте цю функцію лише після інших варіантів. Значення понад 100 істотно сповільнить роботу. %v"
"gapLimitInputErr" = "Невірне значення: дозволено від 1 до 1000."
"viewStats" = "Переглянути статистику"
"dangerZone" = "Небезпечна зона"
"wipeNetworkState" = "Очистити стан мережі"
"wipeNetworkStateBody" = "Це повністю видалить локальний datadir мережі %s (заголовки блоків, кеш пірів, всі гаманці цієї мережі та їхні бази даних). Додаток закриється; запустіть його знову, щоб почати з нуля та відновити гаманці із сід-фрази.\n\nПереконайтеся, що сід-фрази всіх гаманців цієї мережі збережені. Відмінити дію неможливо."
"removeWallet" = "Видалити гаманець з пристрою"
"removeWalletInfo" = "%v Дійсно видалити %v %s%v? Введіть назву гаманця нижче для підтвердження. %v"
"noValidWalletFound" = "Гаманців ще немає"
"createOrRestoreToSeeBalances" = "Створіть або відновіть гаманець Monetarium, щоб побачити баланси VAR і SKA."
"amountReceived" = "Отримано %s %s"
"changeSpendingPass" = "Змінити пароль для витрат"
"setupStartupPassword" = "Налаштувати стартовий пароль"
"startupPasswordEnabled" = "Стартовий пароль увімкнено"
"startupPasswordInfo" = "Стартовий пароль захищає доступ до самого додатка."
"changeWalletName" = "Змінити назву гаманця"
"changeSpecificPeer" = "Змінити піра"
"removePeer" = "Видалити піра"
"userAgent" = "User-Agent"
"changeUserAgent" = "Змінити User-Agent"
"removeUserAgent" = "Видалити User-Agent"
"notifications" = "Сповіщення"
"help" = "Довідка"
"peers" = "Піри"
"beepForNewBlocks" = "Звук на нові блоки"
"viewAppLog" = "Переглянути журнал додатка"
"walletLog" = "Журнал гаманця"
"statistics" = "Статистика"
"bestBlockAge" = "Вік останнього блоку"
"bestBlockTimestamp" = "Час останнього блоку"
"connectedPeersCount" = "Підключених пірів"
"noConnectedPeer" = "Немає підключених пірів"
"walletDirectory" = "Папка гаманця"
"walletStatus" = "Статус гаманця"
"walletSyncing" = "Синхронізація гаманця"
"walletNotSynced" = "Гаманець не синхронізовано"
"connection" = "З'єднання"
"notConnected" = "Не підключено"
"syncingProgress" = "Прогрес синхронізації"
"syncingState" = "Стан синхронізації"
"disconnect" = "Відключити"
"reconnect" = "Перепідключити"
"hideDetails" = "Сховати деталі"

// Asset & balance display
"VAR" = "VAR"
"SKA" = "SKA"
"asset" = "Актив"
"expectedAsset" = "Очікуваний актив"
"allAssets" = "Усі активи"

// Wallet sync states (extras)
"connecting2" = "Підключення до пірів…"
"fetchingHeaders" = "Отримання заголовків блоків…"
"discoveringAddresses" = "Пошук адрес…"
"rescanning" = "Повторне сканування…"
"finalising" = "Завершення…"
`
